const adjustedProducts = [
    {
        id: "001",
        name: "Cámara Dahua IPC-HFW1431S",
        category: "CCTV",
        quantity: 7,
        price: 5200.0,
        location: "Rack 1 - Pasillo 1",
        date: "16/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 15, max: 30 },
            low: { min: 8, max: 14 },
            critical: { max: 7 },
        }, // Actualmente en rango crítico
    },
    {
        id: "002",
        name: "Switch TP-Link T1600G-28PS",
        category: "Redes",
        quantity: 6,
        price: 14500.0,
        location: "Rack 2 - Pasillo 1",
        date: "16/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 10, max: 20 },
            low: { min: 5, max: 9 },
            critical: { max: 4 },
        }, // Actualmente en rango bajo
    },
    {
        id: "003",
        name: "Firewall SonicWall TZ570",
        category: "Seguridad",
        quantity: 3,
        price: 35000.0,
        location: "Pasillo 3 - Rack 1",
        date: "16/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 10, max: 20 },
            low: { min: 5, max: 9 },
            critical: { max: 4 },
        }, // Actualmente en rango crítico
    },
    {
        id: "004",
        name: "Cámara IP Hikvision DS-2CD2143G0-I",
        category: "CCTV",
        quantity: 15,
        price: 2300.0,
        location: "Rack 2 - Pasillo 3",
        date: "18/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 12, max: 20 },
            low: { min: 6, max: 11 },
            critical: { max: 5 },
        }, // Actualmente en rango normal, pero cerca del límite bajo
    },
    {
        id: "005",
        name: "Fuente de alimentación 12V 10A",
        category: "CCTV",
        quantity: 9,
        price: 1500.0,
        location: "Rack 3 - Pasillo 3",
        date: "22/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 20, max: 30 },
            low: { min: 10, max: 19 },
            critical: { max: 9 },
        }, // Actualmente en rango bajo
    },

    {
        id: "006",
        name: "Patch Panel 24 Puertos Cat6",
        category: "Redes",
        quantity: 6,
        price: 2900.0,
        location: "Rack 4 - Pasillo 1",
        date: "23/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 8, max: 15 },
            low: { min: 4, max: 7 },
            critical: { max: 3 },
        },
    },
    {
        id: "007",
        name: "Switch POE Ubiquiti UniFi 8",
        category: "Redes",
        quantity: 12,
        price: 6700.0,
        location: "Rack 1 - Pasillo 3",
        date: "24/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 10, max: 15 },
            low: { min: 5, max: 9 },
            critical: { max: 4 },
        },
    },
    {
        id: "008",
        name: "Extensor de Red TP-Link RE450",
        category: "Redes",
        quantity: 10,
        price: 2500.0,
        location: "Rack 2 - Pasillo 2",
        date: "25/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 15, max: 25 },
            low: { min: 8, max: 14 },
            critical: { max: 7 },
        },
    },
    {
        id: "009",
        name: "Cámara IP Dahua IPC-HFW1230T1",
        category: "CCTV",
        quantity: 20,
        price: 3200.0,
        location: "Rack 3 - Pasillo 2",
        date: "26/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 18, max: 25 },
            low: { min: 10, max: 17 },
            critical: { max: 9 },
        },
    },
    {
        id: "010",
        name: "UPS APC Smart-UPS 1500VA",
        category: "Seguridad",
        quantity: 5,
        price: 25000.0,
        location: "Rack 4 - Pasillo 3",
        date: "27/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 3, max: 8 },
            low: { min: 2, max: 4 },
            critical: { max: 1 },
        },
    },
    {
        id: "011",
        name: "Videograbadora NVR Dahua 8 Canales",
        category: "CCTV",
        quantity: 3,
        price: 15000.0,
        location: "Rack 1 - Pasillo 4",
        date: "28/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 5, max: 10 },
            low: { min: 3, max: 4 },
            critical: { max: 2 },
        },
    },
    {
        id: "012",
        name: "Router TP-Link Archer AX6000",
        category: "Redes",
        quantity: 13,
        price: 8600.0,
        location: "Rack 2 - Pasillo 4",
        date: "29/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 10, max: 18 },
            low: { min: 6, max: 9 },
            critical: { max: 5 },
        },
    },
    {
        id: "013",
        name: "Sirena de alarma inalámbrica",
        category: "Seguridad",
        quantity: 20,
        price: 3200.0,
        location: "Rack 3 - Pasillo 4",
        date: "30/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 18, max: 25 },
            low: { min: 10, max: 17 },
            critical: { max: 9 },
        },
    },
    {
        id: "014",
        name: "Access Point TP-Link EAP225",
        category: "Redes",
        quantity: 9,
        price: 5400.0,
        location: "Rack 4 - Pasillo 2",
        date: "31/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 10, max: 15 },
            low: { min: 5, max: 9 },
            critical: { max: 4 },
        },
    },
    {
        id: "015",
        name: "Cámara IP Uniview IPC3614SR3",
        category: "CCTV",
        quantity: 11,
        price: 8500.0,
        location: "Rack 3 - Pasillo 3",
        date: "01/01/2025",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 10, max: 15 },
            low: { min: 5, max: 9 },
            critical: { max: 4 },
        },
    },
    {
        id: "016",
        name: "Switch D-Link DGS-1100-24",
        category: "Redes",
        quantity: 8,
        price: 7800.0,
        location: "Rack 2 - Pasillo 1",
        date: "02/01/2025",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 10, max: 20 },
            low: { min: 5, max: 9 },
            critical: { max: 4 },
        },
    },
    {
        id: "017",
        name: "Control de Acceso ZKTeco ProFace X",
        category: "Seguridad",
        quantity: 15,
        price: 13500.0,
        location: "Rack 1 - Pasillo 2",
        date: "03/01/2025",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 10, max: 20 },
            low: { min: 5, max: 9 },
            critical: { max: 4 },
        },
    },
    {
        id: "018",
        name: "Cámara PTZ Hikvision DS-2DE3A400",
        category: "CCTV",
        quantity: 7,
        price: 24000.0,
        location: "Rack 3 - Pasillo 4",
        date: "04/01/2025",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 5, max: 10 },
            low: { min: 3, max: 4 },
            critical: { max: 2 },
        },
    },
    {
        id: "019",
        name: "Kit de Alarma Ajax StarterKit Plus",
        category: "Seguridad",
        quantity: 6,
        price: 18600.0,
        location: "Rack 4 - Pasillo 1",
        date: "05/01/2025",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 5, max: 10 },
            low: { min: 3, max: 4 },
            critical: { max: 2 },
        },
    },
    {
        id: "020",
        name: "Switch Aruba Instant On 1930",
        category: "Redes",
        quantity: 17,
        price: 12500.0,
        location: "Rack 1 - Pasillo 3",
        date: "06/01/2025",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 15, max: 20 },
            low: { min: 10, max: 14 },
            critical: { max: 9 },
        },
    },

    {
        id: "021",
        name: "Servidor Dell PowerEdge R650xs",
        category: "Redes",
        quantity: 3,
        price: 190000.0,
        location: "Rack 1 - Pasillo 1",
        date: "21/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 2, max: 5 },
            low: { min: 1, max: 1 },
            critical: { max: 0 },
        },
    },
    {
        id: "022",
        name: "Switch Core Cisco Catalyst 9500",
        category: "Redes",
        quantity: 5,
        price: 150000.0,
        location: "Rack 2 - Pasillo 1",
        date: "22/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 4, max: 6 },
            low: { min: 2, max: 3 },
            critical: { max: 1 },
        },
    },
    {
        id: "023",
        name: "Firewall Palo Alto Networks PA-220",
        category: "Seguridad",
        quantity: 6,
        price: 85000.0,
        location: "Rack 3 - Pasillo 2",
        date: "23/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 5, max: 8 },
            low: { min: 3, max: 4 },
            critical: { max: 2 },
        },
    },
    {
        id: "024",
        name: "Cámara PTZ Bosch AUTODOME IP 5000i",
        category: "CCTV",
        quantity: 4,
        price: 62000.0,
        location: "Rack 4 - Pasillo 3",
        date: "24/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 3, max: 5 },
            low: { min: 1, max: 2 },
            critical: { max: 0 },
        },
    },
    {
        id: "025",
        name: "Control de Acceso Suprema BioEntry P2",
        category: "Seguridad",
        quantity: 8,
        price: 48000.0,
        location: "Rack 1 - Pasillo 4",
        date: "25/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 6, max: 10 },
            low: { min: 3, max: 5 },
            critical: { max: 2 },
        },
    },
    {
        id: "026",
        name: "Servidor HP ProLiant DL380 Gen10",
        category: "Redes",
        quantity: 2,
        price: 250000.0,
        location: "Rack 2 - Pasillo 3",
        date: "26/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 2, max: 3 },
            low: { min: 1, max: 1 },
            critical: { max: 0 },
        },
    },
    {
        id: "027",
        name: "Videograbadora NVR Hikvision DS-9664NI-I8",
        category: "CCTV",
        quantity: 5,
        price: 96000.0,
        location: "Rack 3 - Pasillo 1",
        date: "27/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 4, max: 6 },
            low: { min: 2, max: 3 },
            critical: { max: 1 },
        },
    },
    {
        id: "028",
        name: "Switch Cisco Nexus 9000",
        category: "Redes",
        quantity: 4,
        price: 140000.0,
        location: "Rack 4 - Pasillo 4",
        date: "28/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 3, max: 5 },
            low: { min: 1, max: 2 },
            critical: { max: 0 },
        },
    },
    {
        id: "029",
        name: "Cámara Termográfica Dahua DH-TPC-BF5421",
        category: "CCTV",
        quantity: 3,
        price: 130000.0,
        location: "Rack 2 - Pasillo 4",
        date: "29/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 2, max: 4 },
            low: { min: 1, max: 1 },
            critical: { max: 0 },
        },
    },
    {
        id: "030",
        name: "Sistema de Alarma Ajax Hub 2 Plus",
        category: "Seguridad",
        quantity: 7,
        price: 56000.0,
        location: "Rack 3 - Pasillo 2",
        date: "30/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 5, max: 8 },
            low: { min: 3, max: 4 },
            critical: { max: 2 },
        },
    },
];

export default adjustedProducts;
