const products = [
    {
        id: "001",
        name: "Switch CISCO CATALYST 9200",
        category: "Redes",
        quantity: 20,
        price: 57042.99,
        location: "Pasillo 1 - Rack 2",
        date: "05/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 15, max: 30 },
            low: { min: 10, max: 14 },
            critical: { max: 9 },
        },
    },
    {
        id: "002",
        name: "Firewall Fortinet FortiGate 60F",
        category: "Redes",
        quantity: 20,
        price: 28000.0,
        location: "Pasillo 1 - Rack 2",
        date: "01/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 20, max: 40 },
            low: { min: 10, max: 19 },
            critical: { max: 9 },
        },
    },
    {
        id: "003",
        name: "Router tp-link Archer B550 Wi-Fi 7",
        category: "Redes",
        quantity: 20,
        price: 6720.0,
        location: "Pasillo 2 - Rack 2",
        date: "01/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 15, max: 30 },
            low: { min: 10, max: 14 },
            critical: { max: 9 },
        },
    },

    {
        id: "004",
        name: "Router tp-link Archer C80",
        category: "Redes",
        quantity: 25,
        price: 3800.0,
        location: "Pasillo 1 - Rack 2",
        date: "16/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 20, max: 30 },
            low: { min: 10, max: 19 },
            critical: { max: 9 },
        },
    },
    {
        id: "005",
        name: "Firewall Cisco Firepower 1010",
        category: "Seguridad",
        quantity: 12,
        price: 23000.0,
        location: "Pasillo 3 - Rack 1",
        date: "16/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 15, max: 25 },
            low: { min: 8, max: 14 },
            critical: { max: 7 },
        },
    },
    {
        id: "006",
        name: "Switch MikroTik CRS326",
        category: "Redes",
        quantity: 18,
        price: 7800.0,
        location: "Rack 2 - Pasillo 3",
        date: "16/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 15, max: 20 },
            low: { min: 10, max: 14 },
            critical: { max: 9 },
        },
    },
    {
        id: "007",
        name: "Cámara Dahua IPC-HFW1431S",
        category: "CCTV",
        quantity: 7,
        price: 5200.0,
        location: "Rack 1 - Pasillo 1",
        date: "16/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 15, max: 30 },
            low: { min: 8, max: 14 },
            critical: { max: 7 },
        },
    },
    {
        id: "008",
        name: "Control de Acceso Hikvision DS-K1T804",
        category: "Seguridad",
        quantity: 50,
        price: 9000.0,
        location: "Rack 4 - Pasillo 2",
        date: "16/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 40, max: 60 },
            low: { min: 20, max: 39 },
            critical: { max: 19 },
        },
    },
    {
        id: "009",
        name: "Switch TP-Link T1600G-28PS",
        category: "Redes",
        quantity: 6,
        price: 14500.0,
        location: "Rack 2 - Pasillo 1",
        date: "16/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 10, max: 20 },
            low: { min: 5, max: 9 },
            critical: { max: 4 },
        },
    },
    {
        id: "010",
        name: "Cámara Hikvision DS-2CD2347G2",
        category: "CCTV",
        quantity: 8,
        price: 7800.0,
        location: "Pasillo 1 - Rack 2",
        date: "16/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 15, max: 30 },
            low: { min: 8, max: 14 },
            critical: { max: 7 },
        },
    },
    {
        id: "011",
        name: "Access Point Ubiquiti NanoHD",
        category: "Redes",
        quantity: 20,
        price: 12000.0,
        location: "Rack 3 - Pasillo 1",
        date: "16/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 20, max: 30 },
            low: { min: 10, max: 19 },
            critical: { max: 9 },
        },
    },
    {
        id: "012",
        name: "Sensor de Movimiento Bosch BPR2-WP12",
        category: "Seguridad",
        quantity: 10,
        price: 3200.0,
        location: "Rack 2 - Pasillo 3",
        date: "16/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 10, max: 20 },
            low: { min: 5, max: 9 },
            critical: { max: 4 },
        },
    },
    {
        id: "013",
        name: "Cámara PTZ Dahua SD1A203T-GN",
        category: "CCTV",
        quantity: 15,
        price: 28000.0,
        location: "Rack 1 - Pasillo 1",
        date: "16/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 15, max: 25 },
            low: { min: 8, max: 14 },
            critical: { max: 7 },
        },
    },
    {
        id: "014",
        name: "Switch PoE D-Link DGS-1210-28P",
        category: "Redes",
        quantity: 9,
        price: 11000.0,
        location: "Rack 2 - Pasillo 3",
        date: "16/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 15, max: 20 },
            low: { min: 10, max: 14 },
            critical: { max: 9 },
        },
    },
    {
        id: "015",
        name: "Firewall SonicWall TZ570",
        category: "Seguridad",
        quantity: 3,
        price: 35000.0,
        location: "Pasillo 3 - Rack 1",
        date: "16/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 10, max: 20 },
            low: { min: 5, max: 9 },
            critical: { max: 4 },
        },
    },
    {
        id: "016",
        name: "Router MikroTik hEX RB750Gr3",
        category: "Redes",
        quantity: 18,
        price: 5800.0,
        location: "Rack 4 - Pasillo 2",
        date: "16/12/2024",
        image: "https://via.placeholder.com/50",
        stockRanges: {
            normal: { min: 15, max: 25 },
            low: { min: 8, max: 14 },
            critical: { max: 7 },
        },
    },

];

export default products;
